name: Deploy to Prod
run-name: Prod deploy triggered by ${{ github.actor }}
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy-prod-dbt-job:
    name: "Deploy dbt project to Prod"
    runs-on: ubuntu-latest
    environment: prod   # matches the prod OIDC subject (CICD_PROD_USER)
    env:
      SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}         # CICD_PROD_SERVICE_USER
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}         # FR_CICD_PROD_SERVICE
      SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}  # tasty_bytes_dbt_wh_prod
      SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}    # tasty_bytes_dbt_db
      SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}        # prod

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true

      - run: snow connection test -x

      - name: Deploy dbt project object to Prod
        run: snow dbt deploy tasty_bytes_dbt_project_object_prod --source ./tasty_bytes_dbt_demo --dbt-version 1.11.11 --force -x

      - name: List all of the snowflake dbt project objects on your account
        run: snow dbt list -x

      # (optional) Uncomment the lines below and follow Step 7 if you want to manage Task orchestration via source control
      # - name: Run schedules.sql to create or alter tasks for tasty_bytes_dbt_object_gh_action
      #   run: snow sql -f ${{ github.workspace }}/tasty_bytes/schedules.sql -x
